all:
  hosts:
    openshift_namespace_prod:
      ansible_connection: local
      ansible_host: localhost
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
      openshift_namespace: svc0041p-wordpress
      web2010_host: www.epfl.ch
  vars:
    avi_route_access_level: public-cf
