all:
  hosts:
    openshift_namespace_test:
      ansible_connection: local
      ansible_host: localhost
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
      openshift_namespace: svc0041t-wordpress
      web2010_host: wpn-test.epfl.ch
  vars:
    avi_route_access_level: public
