- name: "web2010 - Image"
  when: >-
    inventory_hostname == "openshift_namespace_test"
  include_tasks:
    file: image.yml
    apply:
      tags:
        - image
  tags:
    - image
    - image.startbuild

- name: "web2010 - App"
  include_tasks:
    file: app.yml
    apply:
      tags:
        - app
  tags:
    - app
    - app.restart
